### ISSUE TITLE
answer 2 numbers

### ISSUE THREAD

**Issue by tossnet** [mwageringel/everest#30] opened 2024-02-13 12:43 UTC
you can't answer 10 for by example 7+3... the field is for only one char

**Comment by mwageringel** [comment] 2024-02-13 20:55
That's intended. Try some other options to find the solution.

**Comment by Pyrukar** [comment] 2024-02-23 22:43
well maybe declare the rules somewhere ... obviously it not the simple rules of math if you cant get past level 1 with this. 

having three combined formulas with the first beeing 5+5= and the others x+1 and x+9 ... the only logical way with normal math would be 5+5=X but your out of luck sloving the rest with only 1 digit. I think few want to try 10^3 combinations just to get to level 2.

**Comment by mwageringel** [comment] 2024-05-28 04:54
I'm closing this, as it's not a bug. As for declaring rules somewhere, that would fall under issue #23.

**Closed as completed by mwageringel** 2024-05-28 04:54 UTC
